customhost = "employee.cila6dkdmjk0.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "christinliewpeimun-employee"
customregion = "us-east-1"
