customhost = "cl-employee.cobcscllth9c.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "clemployee"
custombucket = "cl-employee"
customregion = "us-east-1"
